/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable react-hooks/exhaustive-deps */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import React, { useRef, useEffect, Dispatch, SetStateAction, Ref } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";
import islandScene from "src/assets/3d/tropical_island.glb";
import { Group, Object3DEventMap } from "three";

export interface ModelProps {
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: [number, number, number];
  isRotating?: boolean;
}

interface IslandProps extends ModelProps {
  setIsRotating: Dispatch<SetStateAction<boolean>>;
  setCurrentStage: Dispatch<SetStateAction<number | null>>;
}

const Island: React.FC<IslandProps> = ({
  isRotating,
  setIsRotating,
  setCurrentStage,
  ...props
}) => {
  const islandRef = useRef<Ref<Group<Object3DEventMap>> | null>(null);

  const { gl, viewport } = useThree();
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  //@ts-ignore
  const { nodes, materials } = useGLTF(islandScene);

  // Last horizontal mouse position;
  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e: any) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    // Calculate the clientX based on whether it's a touch event or a mouse event
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;

    // Store the current clientX position for reference
    lastX.current = clientX;
  };

  const handlePointerUp = (e: TouchEvent | MouseEvent): void => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  };

  // Handle pointer (mouse or touch) move event
  const handlePointerMove = (e: any) => {
    e.stopPropagation();
    e.preventDefault();
    if (isRotating) {
      // If rotation is enabled, calculate the change in clientX position
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;

      // calculate the change in the horizontal position of the mouse cursor or touch input,
      // relative to the viewport's width
      const delta = (clientX - lastX.current) / viewport.width;

      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      //@ts-ignore
      // Update the island's rotation based on the mouse/touch movement
      islandRef.current.rotation.y += delta * 0.01 * Math.PI;

      // Update the reference for the last clientX position
      lastX.current = clientX;

      // Update the rotation speed
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === "ArrowLeft") {
      if (!isRotating) setIsRotating(true);
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      //@ts-ignore
      islandRef.current.rotation.y += 0.01 * Math.PI;
    } else if (e.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true);
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      //@ts-ignore
      islandRef.current.rotation.y -= 0.01 * Math.PI;
    }
  };

  const handleKeyUp = (e: KeyboardEvent) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      setIsRotating(false);
    }
  };

  useEffect(() => {
    // Add event listeners for pointer and keyboard events
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);

    // Remove event listeners when component unmounts
    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

  // This function is called on each frame update
  useFrame(() => {
    // If not rotating, apply damping to slow down the rotation (smoothly)
    if (!isRotating) {
      // Apply damping factor
      rotationSpeed.current *= dampingFactor;

      // Stop rotation when speed is very small
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      //@ts-ignore
      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      //@ts-ignore
      // When rotating, determine the current stage based on island's orientation
      const rotation = islandRef.current.rotation.y;

      /**
       * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
       * The goal is to ensure that the rotation value remains within a specific range to
       * prevent potential issues with very large or negative rotation values.
       *  Here's a step-by-step explanation of what this code does:
       *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
       *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
       *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
       *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
       *     This is done to ensure that the value remains positive and within the range of
       *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
       *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
       *     modulo operation to the value obtained in step 2. This step guarantees that the value
       *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
       *     circle in radians.
       */
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
    }
  });

  return (
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    <a.group ref={islandRef} dispose={null} {...props}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="_15cf_Var2_LOD0_0"
                position={[3.492, -0.398, 1.482]}
                rotation={[0.053, -0.004, -0.111]}
                scale={0.01}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Cat_Palm}
                />
              </group>
              <group
                name="_18f6_Var1_LOD0_1"
                position={[-4.135, -0.127, 0.833]}
                rotation={[-0.014, -0.002, 0.105]}
                scale={0.01}
              >
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.Areca_Palm}
                />
              </group>
              <group
                name="_1ffc_Var3_LOD0_2"
                position={[2.461, -0.034, -1.376]}
                rotation={[-0.046, 0.882, -0.101]}
                scale={0.01}
              >
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.Areca_Palm}
                />
              </group>
              <group
                name="_2688_Var3_LOD0_3"
                position={[2.128, -0.253, 1.614]}
                rotation={[0.054, 0, -0.111]}
                scale={0.01}
              >
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.Cat_Palm}
                />
              </group>
              <group
                name="_3b4f_Var2_LOD0_4"
                position={[-1.028, 0.078, 2.394]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
              >
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.Tropical_Palm}
                />
              </group>
              <group
                name="_7303_Var2_LOD0_5"
                position={[1.802, -0.287, 2.491]}
                rotation={[0.132, -0.013, -0.135]}
                scale={0.01}
              >
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.Areca_Palm}
                />
              </group>
              <group
                name="_89e2_Var5_LOD0_6"
                position={[-3.59, -0.085, -0.283]}
                rotation={[-0.014, -0.002, 0.105]}
                scale={0.01}
              >
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.Areca_Palm}
                />
              </group>
              <group
                name="_8b2b_Var4_LOD0_7"
                position={[2.423, -0.143, 0.464]}
                rotation={[0.054, 0, -0.111]}
                scale={0.01}
              >
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.Areca_Palm}
                />
              </group>
              <group
                name="_a2c9_Var3_LOD0_8"
                position={[2.602, -0.299, 1.901]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
              >
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.Tropical_Palm}
                />
              </group>
              <group
                name="_e0f8_Var1_LOD0_9"
                position={[-2.797, 0.038, -1.87]}
                rotation={[Math.PI / 2, 0, -1.124]}
                scale={0.01}
              >
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.Tropical_Palm}
                />
              </group>
              <group
                name="_e1f4_Var1_LOD0_10"
                position={[-4.374, -0.13, -0.19]}
                rotation={[0.091, 0.002, 0.028]}
                scale={0.01}
              >
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.Cat_Palm}
                />
              </group>
              <group
                name="_e74b_Var4_LOD0_11"
                position={[1.968, 0.046, -2.182]}
                rotation={[0.016, 0.669, -0.027]}
                scale={0.01}
              >
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.Cat_Palm}
                />
              </group>
              <group name="Armature_40" position={[-0.28, 0.622, 0]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_31"
                    geometry={nodes.Object_31.geometry}
                    material={materials["Material.001"]}
                    skeleton={nodes.Object_31.skeleton}
                  />
                  <group name="Spiral002_39" />
                </group>
              </group>
              <group
                name="Aset_other__M_ufhsea0fa_LOD2_41"
                position={[-0.023, 0.053, 1.664]}
                rotation={[1.631, -0.021, -1.584]}
              >
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials.Treibholz}
                />
              </group>
              <group
                name="Aset_other_forest_root_M_ufhrfjefa_LOD2_42"
                position={[-0.336, 0.006, -1.974]}
              >
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials.Root}
                />
              </group>
              <group
                name="Aset_rock_assembly_M_udxkec2fa_LOD2_43"
                position={[1.64, -2.196, 12.346]}
              >
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.RocksBig}
                />
              </group>
              <group name="Beach_44" position={[-0.28, 0, 0]}>
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials.BeachBaked}
                />
              </group>
              <group
                name="Palme_45"
                position={[2.076, 0.016, -1.778]}
                rotation={[1.544, -0.079, -2.333]}
              >
                <mesh
                  name="Object_68"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.Palme}
                />
              </group>
              <group
                name="Plane024_46"
                position={[2.844, 3.561, -2.033]}
                rotation={[-3.137, -0.584, -3.103]}
              >
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.Palme_Blaetter}
                />
              </group>
              <group name="RocksSmall_47" position={[-11.774, -1.788, -7.852]}>
                <mesh
                  name="Object_72"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials.RocksSmall}
                />
              </group>
              <group
                name="Skybox_48"
                position={[-0.019, -1.968, 0]}
                rotation={[-Math.PI, -0.788, -Math.PI]}
                scale={0.518}
              >
                <mesh
                  name="Object_74"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={materials["Skybox.001"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
};

export default Island;
